# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c69e277cd0f01e796f8d62b6603d6820e95233184727cdec54442c1aeb251f3901f453929d07f97ae7c9e4a2f65b49e76fc214dc4e77a3ac8367dec96ecc38d

test:
  secret_key_base: 4a2b9457c2b757423e7e8c930ceb2201142cba1cb2eee94ea0f9bac075151ada251ff36bd500e5787502b24232a1d7c628c498ac0f2fdcdb3c4880fe6cfb7e1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
